language: node_js
branches:
  only:
    - master
    - api-v2
    # - /^greenkeeper/.*$/
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8.10.0'
script:
  - npm run test:prod && npm run build
after_success:
  - npm run report-coverage
  - npm run deploy-docs
  # - npm run semantic-release
